### ISSUE TITLE
Suggestions for improvements to docker-based deployments

### ISSUE THREAD

**Issue by sbellem** [drand/drand#371]
This issue is a _draft_ as I just completed setting up a node with docker & docker-compose, I wish to write down a few things that I may otherwise forget. Some of these things will perhaps lead to small PRs to improve the docker-based workflow to deploy a node.

## the `drand` user
Some things to be aware of:
* dedicated `drand` user
* drand home: `/data/drand` is location of the `.drand` directory (`(db, groups, key)`)
* entrypoint: https://github.com/drand/drand/blob/master/docker/entrypoint.sh

If one bypasses the entrypoint, say to work in the container to generate a keypair, or if one `exec` into a running container when the daemon is running, to run the `share` command for instance, then one will be `root` and not `drand` and this can cause problems. In the case of the public/private key generation of the node, the key will get written to `/root/.drand` instead of the expected location `/data/drand`. In the case of the `share` command for the DKG phase, I did not try it as I did not want to screw things up, but my guess is that it may either not work at all, meaning that the command will fail, with no impact on the DKG execution, or it may work but will write under `/root/.drand` which may have some un-expected consequences ... but I don't know.

I am not sure if I am simply working in "un-orthodox" ways with docker, or if perhaps there's some room for some improvements and adjustments.

## the docs (`docker/README.md`)
I followed this documentation for the most part and it was very useful. There are however a few things that may be improved, or corrected.

### volume mount
If I understood correctly the mechanics with the `drand` user, then the volume mount should be

```yml
volumes:
      - ./data:/data/drand/.drand
```

instead of

```yml
volumes:
      - ./data:/root/.drand
```

### entrypoint
the current entrypoint as per the docker-compose.yml file is:

```yml
entrypoint: /drand
```

I am not sure if an entrypoint is needed but I doubt this works, as I think this approach has been deprecated with the recent changes, such that the `drand` command in the docker image is available as `drand` simply as opposed to `/drand`.

### document the entrypoint.sh, its usage and relation to the `drand` user
I think it would be beneficial to document that `entrypoint.sh` and how it switches from `root` to `drand` automatically and what to do if one needs to by pass the entrypoint or one is using `exec` to execute some `drand` command in a running container that is possibly running the `drand` daemon.

I find the approach a bit cumbersome to be frank but perhaps I am unaware of how to work properly with and a bit of documentation would do.

One thing that would, at the very least be useful to clarify is the difference when working in a non-dockerized environment as opposed to working in a dockerized environment. Probably too many words just say: let's document how working with `drand` differs when using the `docker` image.

Perhaps, I miss something, but for instance, why defaulting to different locations for the `.drand` directory, which without `docker` is `$HOME/.drand` meanwhile in docker it is `/data/drand/.drand`? If one knows how to work with `drand` outside docker and then tries to use `docker` one is likely to be confused, and currently the only way to understand seems to look at the `Dockerfile` and `entrypoint.sh`. Some docs to articulate the basics would be useful.

### Are the`drand` user and `DRAND_HOME=/data/drand` really necessary?
I really wonder ... I don't understand the reasoning behind adopting a different behaviour inside and outside a docker container.

I don't think I fully understand what the intended usage is as I am still confused about how one should be using the image and docker-compose when setting up node, meaning when generating the keypair and participating in the DKG setup. But it seems to me that if it was possible to limit the difference between a "native" (non-docker) setup and docker-based setup that would be highly preferable.

## Tasks for PRs
- [x] fix typos in docs (nginx config comment: `// ... --public-listen port` --> `// ... --private-listen port`)
- [ ] update entrypoint in `docker-compose.yml`
- [ ] update volume mount in `docker-compose.yml`
- [ ] docs on how to deal with file permissions for the mounted volume for the `.drand` dir (since the user writing there in docker is `drand`, one may be denied permission outside docker)
- [ ] document docker-based nginx setup (both drand and nginx are run in separate containers under the same overlay network created by docker-compose) -- the nginx config is slightly different and possibly the port mapping(s) in the compose file as well as the arguments to the `drand` command

**Comment by hsanjuan** [comment]
> If one bypasses the entrypoint, say to work in the container to generate a keypair, or if one exec into a running container when the daemon is running, to run the share command for instance, then one will be root and not drand and this can cause problems. 

You don't need to bypass the entrypoint. You can just overwrite the CMD line. In the other case (when doing execs), the "share" is a client command so it is going to talk to the running process which already has the right user (? I think). I realize that switching the user in the entrypoint is suboptimal for exec, but if we did use USER=drand in the Dockerfile and someone needed to actually overwrite the entrypoint to do things that need root it would also be suboptimal.

> Are thedrand user and DRAND_HOME=/data/drand really necessary?

Yes. Normally things are not run with root, even on a dockerized environment. It's meant to be more secure this way.

I think the docker compose template needs to be brought up in line with the container. It shouldn't overwrite the entrypoint as you said.

**Comment by sbellem** [comment]
Ok, I see. Thanks for the feedback!

As a node administrator, I find it useful to work in the container. So, I think it's more a matter of documenting a little bit how to work with the image. For instance:

```
$ docker-compose run --rm --entrypoint='' drand sh
/ # whoami
root

$ docker-compose run --rm --entrypoint='' --user=drand drand sh
/ $ whoami
drand
```

adding the user in the `docker-compose.yml`, also takes care of it:

```yml
services:
  drand:
    image: drandorg/go-drand:latest
    volumes:
      - ./.drand:/data/drand/.drand
    user: drand
    # ...
```

> You don't need to bypass the entrypoint. You can just overwrite the CMD line.
I don't understand. How would you do this? The only way I know currently is as shown above, by overwriting the `entrypoint`.

**Comment by hsanjuan** [comment]
> I don't understand. How would you do this? The only way I know currently is as shown above, by overwriting the `entrypoint`.

Actually I am not sure when using docker-compose. I just meant that if you need to init with different flags or what not you could just `docker run drand start [--your-flags]`. Or if you want to generate a keypair manuallu `docker -v [...] run drand generate-keypair` and then proceed to run the container normally using the same mount.

> Out of curiosity, is there a specific reason for setting the `$HOME` of the `drand` user to `/data/drand` as opposed to `/home/drand`? Although just a detail, I am asking because this differs from the expected location from the point of view of someone who is accustomed to running `drand` without `docker`.

There is no real reason. Dockerfile was inspired in existing dockerfiles which did that.

**Comment by sbellem** [comment]
Yes, I understand when using the `drand` command but there may be situations in which one needs to run commands other than `drand` and thus overriding the entrypoint is then necessary, which is totally okay. One must simply be aware that when doing so one may need to manually switch user, which is also totally fine. It's more a matter of being aware of these details :smile:.
